CREATE DATABASE ReaDaLL CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ReaDaLL;

CREATE TABLE members (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    phone VARCHAR(30) NULL,
    joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB;